export { default as Home } from './Home';
export { default as UserInfo } from './UserInfo';
export { default as InstituteInfo } from './InstituteInfo';
export { default as ClassInfo } from './ClassInfo';
export { default as SubjectInfo } from './SubjectInfo';
export { default as ChapterInfo } from './ChapterInfo';
export { default as TeacherManagement } from './TeacherManagement';
export { default as CreateQuestion } from './CreateQuestion';
export { default as QuestionStatusManagement } from './QuestionStatusManager';
