export const REDUCER_NAME = 'login';
export const FETCH_CURRENT_PROFILE = 'app/state/login/FETCH_CURRENT_PROFILE';
export const FETCH_CURRENT_PROFILE_SUCCESS =
  'app/state/login/FETCH_CURRENT_PROFILE_SUCCESS';
export const SUBMIT_INFO_AND_FETCH_PROFILE =
  'app/state/Login/SUBMIT_INFO_AND_FETCH_PROFILE';
export const SUBMIT_INFO_AND_FETCH_PROFILE_SUCCESS =
  'app/state/Login/SUBMIT_INFO_AND_FETCH_PROFILE_SUCCESS';
export const FETCH_CURRENT_PROFILE_FAILURE =
  'app/state/Login/FETCH_CURRENT_PROFILE_FAILURE';
export const LOGOUT_USER = 'app/state/Login/LOGOUT_USER';
