export const REDUCER_NAME = 'login';
export const SUBMIT_INFO_AND_FETCH_PROFILE =
  'app/state/Login/SUBMIT_INFO_AND_FETCH_PROFILE';
export const SUBMIT_INFO_AND_FETCH_PROFILE_SUCCESS =
  'app/state/Login/SUBMIT_INFO_AND_FETCH_PROFILE_SUCCESS';
