export const REDUCER_NAME = 'headmaster';
export const FETCH_PENDING_TEACHERS = 'FETCH_PENDING_TEACHERS';
export const FETCH_APPROVED_TEACHERS = 'FETCH_APPROVED_TEACHERS';
export const FETCH_PENDING_TEACHERS_SUCCESS = 'FETCH_PENDING_TEACHERS_SUCCESS';
export const FETCH_APPROVED_TEACHERS_SUCCESS =
  'FETCH_APPROVED_TEACHERS_SUCCESS';
