export const REDUCER_NAME = 'headmaster';
export const FETCH_PENDING_TEACHERS = 'FETCH_PENDING_TEACHERS';
export const FETCH_APPROVED_TEACHERS = 'FETCH_APPROVED_TEACHERS';
export const FETCH_PENDING_TEACHERS_SUCCESS = 'FETCH_PENDING_TEACHERS_SUCCESS';
export const FETCH_APPROVED_TEACHERS_SUCCESS =
  'FETCH_APPROVED_TEACHERS_SUCCESS';
export const FETCH_DOWNLOAD_ARCHIVE = 'FETCH_DOWNLOAD_ARCHIVE';
export const FETCH_DOWNLOAD_ARCHIVE_SUCCESS = 'FETCH_DOWNLOAD_ARCHIVE_SUCCESS';
export const FETCH_DOWNLOAD_ARCHIVE_FAILURE = 'FETCH_DOWNLOAD_ARCHIVE_FAILURE';
