package spl.question.bank.database.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CQQuestionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cq_question
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cq_question
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cq_question
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cq_question
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public CQQuestionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cq_question
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cq_question
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cq_question
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cq_question
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cq_question
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cq_question
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cq_question
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cq_question
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cq_question
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cq_question
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cq_question
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStemIsNull() {
            addCriterion("stem is null");
            return (Criteria) this;
        }

        public Criteria andStemIsNotNull() {
            addCriterion("stem is not null");
            return (Criteria) this;
        }

        public Criteria andStemEqualTo(String value) {
            addCriterion("stem =", value, "stem");
            return (Criteria) this;
        }

        public Criteria andStemNotEqualTo(String value) {
            addCriterion("stem <>", value, "stem");
            return (Criteria) this;
        }

        public Criteria andStemGreaterThan(String value) {
            addCriterion("stem >", value, "stem");
            return (Criteria) this;
        }

        public Criteria andStemGreaterThanOrEqualTo(String value) {
            addCriterion("stem >=", value, "stem");
            return (Criteria) this;
        }

        public Criteria andStemLessThan(String value) {
            addCriterion("stem <", value, "stem");
            return (Criteria) this;
        }

        public Criteria andStemLessThanOrEqualTo(String value) {
            addCriterion("stem <=", value, "stem");
            return (Criteria) this;
        }

        public Criteria andStemLike(String value) {
            addCriterion("stem like", value, "stem");
            return (Criteria) this;
        }

        public Criteria andStemNotLike(String value) {
            addCriterion("stem not like", value, "stem");
            return (Criteria) this;
        }

        public Criteria andStemIn(List<String> values) {
            addCriterion("stem in", values, "stem");
            return (Criteria) this;
        }

        public Criteria andStemNotIn(List<String> values) {
            addCriterion("stem not in", values, "stem");
            return (Criteria) this;
        }

        public Criteria andStemBetween(String value1, String value2) {
            addCriterion("stem between", value1, value2, "stem");
            return (Criteria) this;
        }

        public Criteria andStemNotBetween(String value1, String value2) {
            addCriterion("stem not between", value1, value2, "stem");
            return (Criteria) this;
        }

        public Criteria andKnowledgeBasedIsNull() {
            addCriterion("knowledge_based is null");
            return (Criteria) this;
        }

        public Criteria andKnowledgeBasedIsNotNull() {
            addCriterion("knowledge_based is not null");
            return (Criteria) this;
        }

        public Criteria andKnowledgeBasedEqualTo(String value) {
            addCriterion("knowledge_based =", value, "knowledgeBased");
            return (Criteria) this;
        }

        public Criteria andKnowledgeBasedNotEqualTo(String value) {
            addCriterion("knowledge_based <>", value, "knowledgeBased");
            return (Criteria) this;
        }

        public Criteria andKnowledgeBasedGreaterThan(String value) {
            addCriterion("knowledge_based >", value, "knowledgeBased");
            return (Criteria) this;
        }

        public Criteria andKnowledgeBasedGreaterThanOrEqualTo(String value) {
            addCriterion("knowledge_based >=", value, "knowledgeBased");
            return (Criteria) this;
        }

        public Criteria andKnowledgeBasedLessThan(String value) {
            addCriterion("knowledge_based <", value, "knowledgeBased");
            return (Criteria) this;
        }

        public Criteria andKnowledgeBasedLessThanOrEqualTo(String value) {
            addCriterion("knowledge_based <=", value, "knowledgeBased");
            return (Criteria) this;
        }

        public Criteria andKnowledgeBasedLike(String value) {
            addCriterion("knowledge_based like", value, "knowledgeBased");
            return (Criteria) this;
        }

        public Criteria andKnowledgeBasedNotLike(String value) {
            addCriterion("knowledge_based not like", value, "knowledgeBased");
            return (Criteria) this;
        }

        public Criteria andKnowledgeBasedIn(List<String> values) {
            addCriterion("knowledge_based in", values, "knowledgeBased");
            return (Criteria) this;
        }

        public Criteria andKnowledgeBasedNotIn(List<String> values) {
            addCriterion("knowledge_based not in", values, "knowledgeBased");
            return (Criteria) this;
        }

        public Criteria andKnowledgeBasedBetween(String value1, String value2) {
            addCriterion("knowledge_based between", value1, value2, "knowledgeBased");
            return (Criteria) this;
        }

        public Criteria andKnowledgeBasedNotBetween(String value1, String value2) {
            addCriterion("knowledge_based not between", value1, value2, "knowledgeBased");
            return (Criteria) this;
        }

        public Criteria andUnderstandingBasedIsNull() {
            addCriterion("understanding_based is null");
            return (Criteria) this;
        }

        public Criteria andUnderstandingBasedIsNotNull() {
            addCriterion("understanding_based is not null");
            return (Criteria) this;
        }

        public Criteria andUnderstandingBasedEqualTo(String value) {
            addCriterion("understanding_based =", value, "understandingBased");
            return (Criteria) this;
        }

        public Criteria andUnderstandingBasedNotEqualTo(String value) {
            addCriterion("understanding_based <>", value, "understandingBased");
            return (Criteria) this;
        }

        public Criteria andUnderstandingBasedGreaterThan(String value) {
            addCriterion("understanding_based >", value, "understandingBased");
            return (Criteria) this;
        }

        public Criteria andUnderstandingBasedGreaterThanOrEqualTo(String value) {
            addCriterion("understanding_based >=", value, "understandingBased");
            return (Criteria) this;
        }

        public Criteria andUnderstandingBasedLessThan(String value) {
            addCriterion("understanding_based <", value, "understandingBased");
            return (Criteria) this;
        }

        public Criteria andUnderstandingBasedLessThanOrEqualTo(String value) {
            addCriterion("understanding_based <=", value, "understandingBased");
            return (Criteria) this;
        }

        public Criteria andUnderstandingBasedLike(String value) {
            addCriterion("understanding_based like", value, "understandingBased");
            return (Criteria) this;
        }

        public Criteria andUnderstandingBasedNotLike(String value) {
            addCriterion("understanding_based not like", value, "understandingBased");
            return (Criteria) this;
        }

        public Criteria andUnderstandingBasedIn(List<String> values) {
            addCriterion("understanding_based in", values, "understandingBased");
            return (Criteria) this;
        }

        public Criteria andUnderstandingBasedNotIn(List<String> values) {
            addCriterion("understanding_based not in", values, "understandingBased");
            return (Criteria) this;
        }

        public Criteria andUnderstandingBasedBetween(String value1, String value2) {
            addCriterion("understanding_based between", value1, value2, "understandingBased");
            return (Criteria) this;
        }

        public Criteria andUnderstandingBasedNotBetween(String value1, String value2) {
            addCriterion("understanding_based not between", value1, value2, "understandingBased");
            return (Criteria) this;
        }

        public Criteria andApplicationBasedIsNull() {
            addCriterion("application_based is null");
            return (Criteria) this;
        }

        public Criteria andApplicationBasedIsNotNull() {
            addCriterion("application_based is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationBasedEqualTo(String value) {
            addCriterion("application_based =", value, "applicationBased");
            return (Criteria) this;
        }

        public Criteria andApplicationBasedNotEqualTo(String value) {
            addCriterion("application_based <>", value, "applicationBased");
            return (Criteria) this;
        }

        public Criteria andApplicationBasedGreaterThan(String value) {
            addCriterion("application_based >", value, "applicationBased");
            return (Criteria) this;
        }

        public Criteria andApplicationBasedGreaterThanOrEqualTo(String value) {
            addCriterion("application_based >=", value, "applicationBased");
            return (Criteria) this;
        }

        public Criteria andApplicationBasedLessThan(String value) {
            addCriterion("application_based <", value, "applicationBased");
            return (Criteria) this;
        }

        public Criteria andApplicationBasedLessThanOrEqualTo(String value) {
            addCriterion("application_based <=", value, "applicationBased");
            return (Criteria) this;
        }

        public Criteria andApplicationBasedLike(String value) {
            addCriterion("application_based like", value, "applicationBased");
            return (Criteria) this;
        }

        public Criteria andApplicationBasedNotLike(String value) {
            addCriterion("application_based not like", value, "applicationBased");
            return (Criteria) this;
        }

        public Criteria andApplicationBasedIn(List<String> values) {
            addCriterion("application_based in", values, "applicationBased");
            return (Criteria) this;
        }

        public Criteria andApplicationBasedNotIn(List<String> values) {
            addCriterion("application_based not in", values, "applicationBased");
            return (Criteria) this;
        }

        public Criteria andApplicationBasedBetween(String value1, String value2) {
            addCriterion("application_based between", value1, value2, "applicationBased");
            return (Criteria) this;
        }

        public Criteria andApplicationBasedNotBetween(String value1, String value2) {
            addCriterion("application_based not between", value1, value2, "applicationBased");
            return (Criteria) this;
        }

        public Criteria andHigherAbilityIsNull() {
            addCriterion("higher_ability is null");
            return (Criteria) this;
        }

        public Criteria andHigherAbilityIsNotNull() {
            addCriterion("higher_ability is not null");
            return (Criteria) this;
        }

        public Criteria andHigherAbilityEqualTo(String value) {
            addCriterion("higher_ability =", value, "higherAbility");
            return (Criteria) this;
        }

        public Criteria andHigherAbilityNotEqualTo(String value) {
            addCriterion("higher_ability <>", value, "higherAbility");
            return (Criteria) this;
        }

        public Criteria andHigherAbilityGreaterThan(String value) {
            addCriterion("higher_ability >", value, "higherAbility");
            return (Criteria) this;
        }

        public Criteria andHigherAbilityGreaterThanOrEqualTo(String value) {
            addCriterion("higher_ability >=", value, "higherAbility");
            return (Criteria) this;
        }

        public Criteria andHigherAbilityLessThan(String value) {
            addCriterion("higher_ability <", value, "higherAbility");
            return (Criteria) this;
        }

        public Criteria andHigherAbilityLessThanOrEqualTo(String value) {
            addCriterion("higher_ability <=", value, "higherAbility");
            return (Criteria) this;
        }

        public Criteria andHigherAbilityLike(String value) {
            addCriterion("higher_ability like", value, "higherAbility");
            return (Criteria) this;
        }

        public Criteria andHigherAbilityNotLike(String value) {
            addCriterion("higher_ability not like", value, "higherAbility");
            return (Criteria) this;
        }

        public Criteria andHigherAbilityIn(List<String> values) {
            addCriterion("higher_ability in", values, "higherAbility");
            return (Criteria) this;
        }

        public Criteria andHigherAbilityNotIn(List<String> values) {
            addCriterion("higher_ability not in", values, "higherAbility");
            return (Criteria) this;
        }

        public Criteria andHigherAbilityBetween(String value1, String value2) {
            addCriterion("higher_ability between", value1, value2, "higherAbility");
            return (Criteria) this;
        }

        public Criteria andHigherAbilityNotBetween(String value1, String value2) {
            addCriterion("higher_ability not between", value1, value2, "higherAbility");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("weight is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("weight is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(Integer value) {
            addCriterion("weight =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(Integer value) {
            addCriterion("weight <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(Integer value) {
            addCriterion("weight >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("weight >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(Integer value) {
            addCriterion("weight <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(Integer value) {
            addCriterion("weight <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<Integer> values) {
            addCriterion("weight in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<Integer> values) {
            addCriterion("weight not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(Integer value1, Integer value2) {
            addCriterion("weight between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("weight not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(Integer value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(Integer value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(Integer value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(Integer value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(Integer value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(Integer value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<Integer> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<Integer> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(Integer value1, Integer value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(Integer value1, Integer value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIsNull() {
            addCriterion("subject_id is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIsNotNull() {
            addCriterion("subject_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectIdEqualTo(Integer value) {
            addCriterion("subject_id =", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotEqualTo(Integer value) {
            addCriterion("subject_id <>", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdGreaterThan(Integer value) {
            addCriterion("subject_id >", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("subject_id >=", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdLessThan(Integer value) {
            addCriterion("subject_id <", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("subject_id <=", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIn(List<Integer> values) {
            addCriterion("subject_id in", values, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotIn(List<Integer> values) {
            addCriterion("subject_id not in", values, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdBetween(Integer value1, Integer value2) {
            addCriterion("subject_id between", value1, value2, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("subject_id not between", value1, value2, "subjectId");
            return (Criteria) this;
        }

        public Criteria andChapterIdIsNull() {
            addCriterion("chapter_id is null");
            return (Criteria) this;
        }

        public Criteria andChapterIdIsNotNull() {
            addCriterion("chapter_id is not null");
            return (Criteria) this;
        }

        public Criteria andChapterIdEqualTo(Integer value) {
            addCriterion("chapter_id =", value, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdNotEqualTo(Integer value) {
            addCriterion("chapter_id <>", value, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdGreaterThan(Integer value) {
            addCriterion("chapter_id >", value, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("chapter_id >=", value, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdLessThan(Integer value) {
            addCriterion("chapter_id <", value, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdLessThanOrEqualTo(Integer value) {
            addCriterion("chapter_id <=", value, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdIn(List<Integer> values) {
            addCriterion("chapter_id in", values, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdNotIn(List<Integer> values) {
            addCriterion("chapter_id not in", values, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdBetween(Integer value1, Integer value2) {
            addCriterion("chapter_id between", value1, value2, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdNotBetween(Integer value1, Integer value2) {
            addCriterion("chapter_id not between", value1, value2, "chapterId");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andModeratedAtIsNull() {
            addCriterion("moderated_at is null");
            return (Criteria) this;
        }

        public Criteria andModeratedAtIsNotNull() {
            addCriterion("moderated_at is not null");
            return (Criteria) this;
        }

        public Criteria andModeratedAtEqualTo(Date value) {
            addCriterion("moderated_at =", value, "moderatedAt");
            return (Criteria) this;
        }

        public Criteria andModeratedAtNotEqualTo(Date value) {
            addCriterion("moderated_at <>", value, "moderatedAt");
            return (Criteria) this;
        }

        public Criteria andModeratedAtGreaterThan(Date value) {
            addCriterion("moderated_at >", value, "moderatedAt");
            return (Criteria) this;
        }

        public Criteria andModeratedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("moderated_at >=", value, "moderatedAt");
            return (Criteria) this;
        }

        public Criteria andModeratedAtLessThan(Date value) {
            addCriterion("moderated_at <", value, "moderatedAt");
            return (Criteria) this;
        }

        public Criteria andModeratedAtLessThanOrEqualTo(Date value) {
            addCriterion("moderated_at <=", value, "moderatedAt");
            return (Criteria) this;
        }

        public Criteria andModeratedAtIn(List<Date> values) {
            addCriterion("moderated_at in", values, "moderatedAt");
            return (Criteria) this;
        }

        public Criteria andModeratedAtNotIn(List<Date> values) {
            addCriterion("moderated_at not in", values, "moderatedAt");
            return (Criteria) this;
        }

        public Criteria andModeratedAtBetween(Date value1, Date value2) {
            addCriterion("moderated_at between", value1, value2, "moderatedAt");
            return (Criteria) this;
        }

        public Criteria andModeratedAtNotBetween(Date value1, Date value2) {
            addCriterion("moderated_at not between", value1, value2, "moderatedAt");
            return (Criteria) this;
        }

        public Criteria andModeratedByIsNull() {
            addCriterion("moderated_by is null");
            return (Criteria) this;
        }

        public Criteria andModeratedByIsNotNull() {
            addCriterion("moderated_by is not null");
            return (Criteria) this;
        }

        public Criteria andModeratedByEqualTo(Integer value) {
            addCriterion("moderated_by =", value, "moderatedBy");
            return (Criteria) this;
        }

        public Criteria andModeratedByNotEqualTo(Integer value) {
            addCriterion("moderated_by <>", value, "moderatedBy");
            return (Criteria) this;
        }

        public Criteria andModeratedByGreaterThan(Integer value) {
            addCriterion("moderated_by >", value, "moderatedBy");
            return (Criteria) this;
        }

        public Criteria andModeratedByGreaterThanOrEqualTo(Integer value) {
            addCriterion("moderated_by >=", value, "moderatedBy");
            return (Criteria) this;
        }

        public Criteria andModeratedByLessThan(Integer value) {
            addCriterion("moderated_by <", value, "moderatedBy");
            return (Criteria) this;
        }

        public Criteria andModeratedByLessThanOrEqualTo(Integer value) {
            addCriterion("moderated_by <=", value, "moderatedBy");
            return (Criteria) this;
        }

        public Criteria andModeratedByIn(List<Integer> values) {
            addCriterion("moderated_by in", values, "moderatedBy");
            return (Criteria) this;
        }

        public Criteria andModeratedByNotIn(List<Integer> values) {
            addCriterion("moderated_by not in", values, "moderatedBy");
            return (Criteria) this;
        }

        public Criteria andModeratedByBetween(Integer value1, Integer value2) {
            addCriterion("moderated_by between", value1, value2, "moderatedBy");
            return (Criteria) this;
        }

        public Criteria andModeratedByNotBetween(Integer value1, Integer value2) {
            addCriterion("moderated_by not between", value1, value2, "moderatedBy");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andDifficultyIsNull() {
            addCriterion("difficulty is null");
            return (Criteria) this;
        }

        public Criteria andDifficultyIsNotNull() {
            addCriterion("difficulty is not null");
            return (Criteria) this;
        }

        public Criteria andDifficultyEqualTo(String value) {
            addCriterion("difficulty =", value, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyNotEqualTo(String value) {
            addCriterion("difficulty <>", value, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyGreaterThan(String value) {
            addCriterion("difficulty >", value, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyGreaterThanOrEqualTo(String value) {
            addCriterion("difficulty >=", value, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyLessThan(String value) {
            addCriterion("difficulty <", value, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyLessThanOrEqualTo(String value) {
            addCriterion("difficulty <=", value, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyLike(String value) {
            addCriterion("difficulty like", value, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyNotLike(String value) {
            addCriterion("difficulty not like", value, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyIn(List<String> values) {
            addCriterion("difficulty in", values, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyNotIn(List<String> values) {
            addCriterion("difficulty not in", values, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyBetween(String value1, String value2) {
            addCriterion("difficulty between", value1, value2, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyNotBetween(String value1, String value2) {
            addCriterion("difficulty not between", value1, value2, "difficulty");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cq_question
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 12 23:05:49 BDT 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cq_question
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}