package spl.question.bank.database.model;

import java.io.Serializable;
import java.util.Date;

public class CQQuestion implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_question.id
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_question.stem
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    private String stem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_question.knowledge_based
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    private String knowledgeBased;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_question.understanding_based
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    private String understandingBased;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_question.application_based
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    private String applicationBased;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_question.higher_ability
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    private String higherAbility;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_question.weight
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    private Integer weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_question.created_by
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_question.subject_id
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    private Integer subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_question.chapter_id
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    private Integer chapterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_question.created_at
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_question.moderated_at
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    private Date moderatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_question.moderated_by
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    private Integer moderatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_question.status
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_question.difficulty
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    private String difficulty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cq_question
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_question.id
     *
     * @return the value of cq_question.id
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_question.id
     *
     * @param id the value for cq_question.id
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_question.stem
     *
     * @return the value of cq_question.stem
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public String getStem() {
        return stem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_question.stem
     *
     * @param stem the value for cq_question.stem
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public void setStem(String stem) {
        this.stem = stem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_question.knowledge_based
     *
     * @return the value of cq_question.knowledge_based
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public String getKnowledgeBased() {
        return knowledgeBased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_question.knowledge_based
     *
     * @param knowledgeBased the value for cq_question.knowledge_based
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public void setKnowledgeBased(String knowledgeBased) {
        this.knowledgeBased = knowledgeBased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_question.understanding_based
     *
     * @return the value of cq_question.understanding_based
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public String getUnderstandingBased() {
        return understandingBased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_question.understanding_based
     *
     * @param understandingBased the value for cq_question.understanding_based
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public void setUnderstandingBased(String understandingBased) {
        this.understandingBased = understandingBased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_question.application_based
     *
     * @return the value of cq_question.application_based
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public String getApplicationBased() {
        return applicationBased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_question.application_based
     *
     * @param applicationBased the value for cq_question.application_based
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public void setApplicationBased(String applicationBased) {
        this.applicationBased = applicationBased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_question.higher_ability
     *
     * @return the value of cq_question.higher_ability
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public String getHigherAbility() {
        return higherAbility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_question.higher_ability
     *
     * @param higherAbility the value for cq_question.higher_ability
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public void setHigherAbility(String higherAbility) {
        this.higherAbility = higherAbility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_question.weight
     *
     * @return the value of cq_question.weight
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_question.weight
     *
     * @param weight the value for cq_question.weight
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_question.created_by
     *
     * @return the value of cq_question.created_by
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_question.created_by
     *
     * @param createdBy the value for cq_question.created_by
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_question.subject_id
     *
     * @return the value of cq_question.subject_id
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_question.subject_id
     *
     * @param subjectId the value for cq_question.subject_id
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_question.chapter_id
     *
     * @return the value of cq_question.chapter_id
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public Integer getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_question.chapter_id
     *
     * @param chapterId the value for cq_question.chapter_id
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public void setChapterId(Integer chapterId) {
        this.chapterId = chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_question.created_at
     *
     * @return the value of cq_question.created_at
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_question.created_at
     *
     * @param createdAt the value for cq_question.created_at
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_question.moderated_at
     *
     * @return the value of cq_question.moderated_at
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public Date getModeratedAt() {
        return moderatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_question.moderated_at
     *
     * @param moderatedAt the value for cq_question.moderated_at
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public void setModeratedAt(Date moderatedAt) {
        this.moderatedAt = moderatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_question.moderated_by
     *
     * @return the value of cq_question.moderated_by
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public Integer getModeratedBy() {
        return moderatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_question.moderated_by
     *
     * @param moderatedBy the value for cq_question.moderated_by
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public void setModeratedBy(Integer moderatedBy) {
        this.moderatedBy = moderatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_question.status
     *
     * @return the value of cq_question.status
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_question.status
     *
     * @param status the value for cq_question.status
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_question.difficulty
     *
     * @return the value of cq_question.difficulty
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public String getDifficulty() {
        return difficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_question.difficulty
     *
     * @param difficulty the value for cq_question.difficulty
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    public void setDifficulty(String difficulty) {
        this.difficulty = difficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cq_question
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CQQuestion other = (CQQuestion) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getStem() == null ? other.getStem() == null : this.getStem().equals(other.getStem()))
            && (this.getKnowledgeBased() == null ? other.getKnowledgeBased() == null : this.getKnowledgeBased().equals(other.getKnowledgeBased()))
            && (this.getUnderstandingBased() == null ? other.getUnderstandingBased() == null : this.getUnderstandingBased().equals(other.getUnderstandingBased()))
            && (this.getApplicationBased() == null ? other.getApplicationBased() == null : this.getApplicationBased().equals(other.getApplicationBased()))
            && (this.getHigherAbility() == null ? other.getHigherAbility() == null : this.getHigherAbility().equals(other.getHigherAbility()))
            && (this.getWeight() == null ? other.getWeight() == null : this.getWeight().equals(other.getWeight()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()))
            && (this.getSubjectId() == null ? other.getSubjectId() == null : this.getSubjectId().equals(other.getSubjectId()))
            && (this.getChapterId() == null ? other.getChapterId() == null : this.getChapterId().equals(other.getChapterId()))
            && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()))
            && (this.getModeratedAt() == null ? other.getModeratedAt() == null : this.getModeratedAt().equals(other.getModeratedAt()))
            && (this.getModeratedBy() == null ? other.getModeratedBy() == null : this.getModeratedBy().equals(other.getModeratedBy()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getDifficulty() == null ? other.getDifficulty() == null : this.getDifficulty().equals(other.getDifficulty()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cq_question
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getStem() == null) ? 0 : getStem().hashCode());
        result = prime * result + ((getKnowledgeBased() == null) ? 0 : getKnowledgeBased().hashCode());
        result = prime * result + ((getUnderstandingBased() == null) ? 0 : getUnderstandingBased().hashCode());
        result = prime * result + ((getApplicationBased() == null) ? 0 : getApplicationBased().hashCode());
        result = prime * result + ((getHigherAbility() == null) ? 0 : getHigherAbility().hashCode());
        result = prime * result + ((getWeight() == null) ? 0 : getWeight().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        result = prime * result + ((getSubjectId() == null) ? 0 : getSubjectId().hashCode());
        result = prime * result + ((getChapterId() == null) ? 0 : getChapterId().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        result = prime * result + ((getModeratedAt() == null) ? 0 : getModeratedAt().hashCode());
        result = prime * result + ((getModeratedBy() == null) ? 0 : getModeratedBy().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getDifficulty() == null) ? 0 : getDifficulty().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cq_question
     *
     * @mbg.generated Thu Dec 12 23:05:49 BDT 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", stem=").append(stem);
        sb.append(", knowledgeBased=").append(knowledgeBased);
        sb.append(", understandingBased=").append(understandingBased);
        sb.append(", applicationBased=").append(applicationBased);
        sb.append(", higherAbility=").append(higherAbility);
        sb.append(", weight=").append(weight);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", subjectId=").append(subjectId);
        sb.append(", chapterId=").append(chapterId);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", moderatedAt=").append(moderatedAt);
        sb.append(", moderatedBy=").append(moderatedBy);
        sb.append(", status=").append(status);
        sb.append(", difficulty=").append(difficulty);
        sb.append("]");
        return sb.toString();
    }
}