package spl.question.bank.database.model;

import java.io.Serializable;

public class Institute implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institute.id
     *
     * @mbg.generated Fri Sep 20 09:20:26 BDT 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institute.name
     *
     * @mbg.generated Fri Sep 20 09:20:26 BDT 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institute.eiin_number
     *
     * @mbg.generated Fri Sep 20 09:20:26 BDT 2019
     */
    private Integer eiinNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table institute
     *
     * @mbg.generated Fri Sep 20 09:20:26 BDT 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institute.id
     *
     * @return the value of institute.id
     *
     * @mbg.generated Fri Sep 20 09:20:26 BDT 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institute.id
     *
     * @param id the value for institute.id
     *
     * @mbg.generated Fri Sep 20 09:20:26 BDT 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institute.name
     *
     * @return the value of institute.name
     *
     * @mbg.generated Fri Sep 20 09:20:26 BDT 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institute.name
     *
     * @param name the value for institute.name
     *
     * @mbg.generated Fri Sep 20 09:20:26 BDT 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institute.eiin_number
     *
     * @return the value of institute.eiin_number
     *
     * @mbg.generated Fri Sep 20 09:20:26 BDT 2019
     */
    public Integer getEiinNumber() {
        return eiinNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institute.eiin_number
     *
     * @param eiinNumber the value for institute.eiin_number
     *
     * @mbg.generated Fri Sep 20 09:20:26 BDT 2019
     */
    public void setEiinNumber(Integer eiinNumber) {
        this.eiinNumber = eiinNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institute
     *
     * @mbg.generated Fri Sep 20 09:20:26 BDT 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Institute other = (Institute) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getEiinNumber() == null ? other.getEiinNumber() == null : this.getEiinNumber().equals(other.getEiinNumber()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institute
     *
     * @mbg.generated Fri Sep 20 09:20:26 BDT 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getEiinNumber() == null) ? 0 : getEiinNumber().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institute
     *
     * @mbg.generated Fri Sep 20 09:20:26 BDT 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", eiinNumber=").append(eiinNumber);
        sb.append("]");
        return sb.toString();
    }
}