package spl.question.bank.database.model;

import java.io.Serializable;

public class LearningOutcome implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_outcome.id
     *
     * @mbg.generated Sat Nov 30 21:02:28 BDT 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_outcome.outcome
     *
     * @mbg.generated Sat Nov 30 21:02:28 BDT 2019
     */
    private String outcome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_outcome.chapter_id
     *
     * @mbg.generated Sat Nov 30 21:02:28 BDT 2019
     */
    private Integer chapterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_outcome.subject_id
     *
     * @mbg.generated Sat Nov 30 21:02:28 BDT 2019
     */
    private Integer subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_outcome.class_id
     *
     * @mbg.generated Sat Nov 30 21:02:28 BDT 2019
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table learning_outcome
     *
     * @mbg.generated Sat Nov 30 21:02:28 BDT 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_outcome.id
     *
     * @return the value of learning_outcome.id
     *
     * @mbg.generated Sat Nov 30 21:02:28 BDT 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_outcome.id
     *
     * @param id the value for learning_outcome.id
     *
     * @mbg.generated Sat Nov 30 21:02:28 BDT 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_outcome.outcome
     *
     * @return the value of learning_outcome.outcome
     *
     * @mbg.generated Sat Nov 30 21:02:28 BDT 2019
     */
    public String getOutcome() {
        return outcome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_outcome.outcome
     *
     * @param outcome the value for learning_outcome.outcome
     *
     * @mbg.generated Sat Nov 30 21:02:28 BDT 2019
     */
    public void setOutcome(String outcome) {
        this.outcome = outcome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_outcome.chapter_id
     *
     * @return the value of learning_outcome.chapter_id
     *
     * @mbg.generated Sat Nov 30 21:02:28 BDT 2019
     */
    public Integer getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_outcome.chapter_id
     *
     * @param chapterId the value for learning_outcome.chapter_id
     *
     * @mbg.generated Sat Nov 30 21:02:28 BDT 2019
     */
    public void setChapterId(Integer chapterId) {
        this.chapterId = chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_outcome.subject_id
     *
     * @return the value of learning_outcome.subject_id
     *
     * @mbg.generated Sat Nov 30 21:02:28 BDT 2019
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_outcome.subject_id
     *
     * @param subjectId the value for learning_outcome.subject_id
     *
     * @mbg.generated Sat Nov 30 21:02:28 BDT 2019
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_outcome.class_id
     *
     * @return the value of learning_outcome.class_id
     *
     * @mbg.generated Sat Nov 30 21:02:28 BDT 2019
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_outcome.class_id
     *
     * @param classId the value for learning_outcome.class_id
     *
     * @mbg.generated Sat Nov 30 21:02:28 BDT 2019
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learning_outcome
     *
     * @mbg.generated Sat Nov 30 21:02:28 BDT 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LearningOutcome other = (LearningOutcome) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOutcome() == null ? other.getOutcome() == null : this.getOutcome().equals(other.getOutcome()))
            && (this.getChapterId() == null ? other.getChapterId() == null : this.getChapterId().equals(other.getChapterId()))
            && (this.getSubjectId() == null ? other.getSubjectId() == null : this.getSubjectId().equals(other.getSubjectId()))
            && (this.getClassId() == null ? other.getClassId() == null : this.getClassId().equals(other.getClassId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learning_outcome
     *
     * @mbg.generated Sat Nov 30 21:02:28 BDT 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOutcome() == null) ? 0 : getOutcome().hashCode());
        result = prime * result + ((getChapterId() == null) ? 0 : getChapterId().hashCode());
        result = prime * result + ((getSubjectId() == null) ? 0 : getSubjectId().hashCode());
        result = prime * result + ((getClassId() == null) ? 0 : getClassId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learning_outcome
     *
     * @mbg.generated Sat Nov 30 21:02:28 BDT 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", outcome=").append(outcome);
        sb.append(", chapterId=").append(chapterId);
        sb.append(", subjectId=").append(subjectId);
        sb.append(", classId=").append(classId);
        sb.append("]");
        return sb.toString();
    }
}