package spl.question.bank.database.model;

import java.io.Serializable;
import java.util.Date;

public class QuestionPaper implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_paper.id
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_paper.type
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_paper.subject_id
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    private Integer subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_paper.created_at
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_paper.generated_by
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    private Integer generatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_paper.exam_type
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    private String examType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_paper.duration
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    private String duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_paper.institute_name
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    private String instituteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_paper.total_marks
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    private Integer totalMarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question_paper
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_paper.id
     *
     * @return the value of question_paper.id
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_paper.id
     *
     * @param id the value for question_paper.id
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_paper.type
     *
     * @return the value of question_paper.type
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_paper.type
     *
     * @param type the value for question_paper.type
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_paper.subject_id
     *
     * @return the value of question_paper.subject_id
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_paper.subject_id
     *
     * @param subjectId the value for question_paper.subject_id
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_paper.created_at
     *
     * @return the value of question_paper.created_at
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_paper.created_at
     *
     * @param createdAt the value for question_paper.created_at
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_paper.generated_by
     *
     * @return the value of question_paper.generated_by
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    public Integer getGeneratedBy() {
        return generatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_paper.generated_by
     *
     * @param generatedBy the value for question_paper.generated_by
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    public void setGeneratedBy(Integer generatedBy) {
        this.generatedBy = generatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_paper.exam_type
     *
     * @return the value of question_paper.exam_type
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    public String getExamType() {
        return examType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_paper.exam_type
     *
     * @param examType the value for question_paper.exam_type
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    public void setExamType(String examType) {
        this.examType = examType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_paper.duration
     *
     * @return the value of question_paper.duration
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_paper.duration
     *
     * @param duration the value for question_paper.duration
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    public void setDuration(String duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_paper.institute_name
     *
     * @return the value of question_paper.institute_name
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    public String getInstituteName() {
        return instituteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_paper.institute_name
     *
     * @param instituteName the value for question_paper.institute_name
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    public void setInstituteName(String instituteName) {
        this.instituteName = instituteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_paper.total_marks
     *
     * @return the value of question_paper.total_marks
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    public Integer getTotalMarks() {
        return totalMarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_paper.total_marks
     *
     * @param totalMarks the value for question_paper.total_marks
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    public void setTotalMarks(Integer totalMarks) {
        this.totalMarks = totalMarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_paper
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        QuestionPaper other = (QuestionPaper) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getSubjectId() == null ? other.getSubjectId() == null : this.getSubjectId().equals(other.getSubjectId()))
            && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()))
            && (this.getGeneratedBy() == null ? other.getGeneratedBy() == null : this.getGeneratedBy().equals(other.getGeneratedBy()))
            && (this.getExamType() == null ? other.getExamType() == null : this.getExamType().equals(other.getExamType()))
            && (this.getDuration() == null ? other.getDuration() == null : this.getDuration().equals(other.getDuration()))
            && (this.getInstituteName() == null ? other.getInstituteName() == null : this.getInstituteName().equals(other.getInstituteName()))
            && (this.getTotalMarks() == null ? other.getTotalMarks() == null : this.getTotalMarks().equals(other.getTotalMarks()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_paper
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getSubjectId() == null) ? 0 : getSubjectId().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        result = prime * result + ((getGeneratedBy() == null) ? 0 : getGeneratedBy().hashCode());
        result = prime * result + ((getExamType() == null) ? 0 : getExamType().hashCode());
        result = prime * result + ((getDuration() == null) ? 0 : getDuration().hashCode());
        result = prime * result + ((getInstituteName() == null) ? 0 : getInstituteName().hashCode());
        result = prime * result + ((getTotalMarks() == null) ? 0 : getTotalMarks().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_paper
     *
     * @mbg.generated Mon Dec 16 23:28:16 BDT 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", subjectId=").append(subjectId);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", generatedBy=").append(generatedBy);
        sb.append(", examType=").append(examType);
        sb.append(", duration=").append(duration);
        sb.append(", instituteName=").append(instituteName);
        sb.append(", totalMarks=").append(totalMarks);
        sb.append("]");
        return sb.toString();
    }
}