package spl.question.bank.database.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.firstName
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lastName
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.permanentAddress
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    private String permanentaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.tempAddress
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    private String tempaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birth_date
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    private Date birthDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.join_date
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    private Date joinDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.firstName
     *
     * @return the value of user.firstName
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.firstName
     *
     * @param firstname the value for user.firstName
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lastName
     *
     * @return the value of user.lastName
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lastName
     *
     * @param lastname the value for user.lastName
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.permanentAddress
     *
     * @return the value of user.permanentAddress
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    public String getPermanentaddress() {
        return permanentaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.permanentAddress
     *
     * @param permanentaddress the value for user.permanentAddress
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    public void setPermanentaddress(String permanentaddress) {
        this.permanentaddress = permanentaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.tempAddress
     *
     * @return the value of user.tempAddress
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    public String getTempaddress() {
        return tempaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.tempAddress
     *
     * @param tempaddress the value for user.tempAddress
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    public void setTempaddress(String tempaddress) {
        this.tempaddress = tempaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birth_date
     *
     * @return the value of user.birth_date
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birth_date
     *
     * @param birthDate the value for user.birth_date
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.join_date
     *
     * @return the value of user.join_date
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    public Date getJoinDate() {
        return joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.join_date
     *
     * @param joinDate the value for user.join_date
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getFirstname() == null ? other.getFirstname() == null : this.getFirstname().equals(other.getFirstname()))
            && (this.getLastname() == null ? other.getLastname() == null : this.getLastname().equals(other.getLastname()))
            && (this.getPermanentaddress() == null ? other.getPermanentaddress() == null : this.getPermanentaddress().equals(other.getPermanentaddress()))
            && (this.getTempaddress() == null ? other.getTempaddress() == null : this.getTempaddress().equals(other.getTempaddress()))
            && (this.getBirthDate() == null ? other.getBirthDate() == null : this.getBirthDate().equals(other.getBirthDate()))
            && (this.getJoinDate() == null ? other.getJoinDate() == null : this.getJoinDate().equals(other.getJoinDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getFirstname() == null) ? 0 : getFirstname().hashCode());
        result = prime * result + ((getLastname() == null) ? 0 : getLastname().hashCode());
        result = prime * result + ((getPermanentaddress() == null) ? 0 : getPermanentaddress().hashCode());
        result = prime * result + ((getTempaddress() == null) ? 0 : getTempaddress().hashCode());
        result = prime * result + ((getBirthDate() == null) ? 0 : getBirthDate().hashCode());
        result = prime * result + ((getJoinDate() == null) ? 0 : getJoinDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Jun 20 19:57:23 BDT 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", email=").append(email);
        sb.append(", password=").append(password);
        sb.append(", firstname=").append(firstname);
        sb.append(", lastname=").append(lastname);
        sb.append(", permanentaddress=").append(permanentaddress);
        sb.append(", tempaddress=").append(tempaddress);
        sb.append(", birthDate=").append(birthDate);
        sb.append(", joinDate=").append(joinDate);
        sb.append("]");
        return sb.toString();
    }
}